### ISSUE TITLE
yii wrapper

### ISSUE THREAD

**Issue by blackout314** [kbsali/php-redmine-api#107] opened 2015-01-26 21:12 UTC
Hi mate,
FYI https://github.com/blackout314/yii-php-redmine-api :+1:

**Comment by kbsali** [comment] 2015-01-26 21:27
@blackout314 great!
How about using composer so you don't have to manually import the updates of php-redmine-api back to your repository?
plenty of examples available : https://packagist.org/search/?q=yii

**Comment by kbsali** [comment] 2015-01-26 21:28
(closing as this not a bug, but a good news! ;))

**Closed by kbsali** 2015-01-26 21:27 UTC
