### ISSUE TITLE
runRequest return empty message

### ISSUE THREAD

**Issue by nguyenthemanh2601** [kbsali/php-redmine-api#256] opened 2021-03-18 10:39 UTC
I am try to login to redmine.
But when i call: (new Redmine\Client(env('URL_REDMINE'), $username, $password))->->user->getCurrentUser();

an empty exception have been display

With $path = /users/current.json?include=memberships%2Cgroups pass by Redmine\Api\User->show(),
curl_errno($curl) on runRequest method is 3, but curl_error($curl) is empty.

It is CURLE_URL_MALFORMAT error, but $path is default on show method.

**Comment by Art4** [comment] 2021-03-19 14:00
Hey, I can't reproduce this on my machine. The `$path` is correct and returns the correct data.
 
Please make sure that `env('URL_REDMINE')` will return a valid url without a trailing slash (`/`).

**Comment by Art4** [comment] 2021-12-14 15:23
Hey, it's been a while since the last activity here, so I'm closing the ticket.

Feel free to comment if there are any new findings and then we'll reopen the ticket.

**Closed by Art4** 2021-12-14 15:23 UTC
Labels: pending: await feedback, possible bug
